# iNeuron 

## DLCVNLP (Deep Learning - Computer Vision - Natural Language Processing)
## Numpy Assignment


### Question 1
Write a function so that the columns of the output matrix are powers of the input
vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

**HINT:** Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [40]:
input = [1,2,3,4,5,6]

def get_vander_matrix(input, n=3):
    length = len(input)
    res = np.zeros((length, n)).astype('int')
    for i in range(length):
        for j in range(n):
            res[i][j] = input[i]**j
    return res

print( get_vander_matrix(input, 7) )

[[    1     1     1     1     1     1     1]
 [    1     2     4     8    16    32    64]
 [    1     3     9    27    81   243   729]
 [    1     4    16    64   256  1024  4096]
 [    1     5    25   125   625  3125 15625]
 [    1     6    36   216  1296  7776 46656]]


### Problem Statement
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:

The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below

  i  1  2  3  4  5  6  7  8  9  10

===== == == == == == == == == == ==

Input 10 20 30 40 50 60 70 80 90 100

y1 25 = (10+20+30+40)/4

y2 35 = (20+30+40+50)/4

y3 45 = (30+40+50+60)/4

y4 55 = (40+50+60+70)/4

y5 65 = (50+60+70+80)/4

y6 75 = (60+70+80+90)/4

y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

### Question 2
Write a function to find moving average in an array over a window:

Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [41]:
def get_moving_averages(input, k=3):
    n = len(input)
    res = []
    for i in range(n-k+1):
        local_sum = 0
        for j in range(k):
            local_sum += input[i+j]
        res.append(local_sum)
    return res

print( get_moving_averages([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150], 3) )

[15, 14, 17, 20, 29, 86, 148, 218, 252, 280, 349]
