# iNeuron
## Python
## Assignment 3

###  Introduction
This assignment will help you to consolidate the concepts learnt in the session.

### Task 1
Write a function to compute 5/0 and use try/except to catch the exceptions.


In [10]:
def compute_5_divided_by_0(): 
    res = None
    try:
        res = 5/0
    except:
        print("Exception occurred while dividing by 0")
        
print( compute_5_divided_by_0() )

Exception occurred while dividing by 0
None


### Task 2
Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and 

verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"] verbs=["play","watch"] objects=["Baseball","Cricket"]
Output should come as below:

Americans play Baseball.
Americans play Cricket. 
Americans watch Baseball. 
Americans watch Cricket. 
Indians play Baseball. 
Indians play Cricket. 
Indians watch Baseball. 
Indians watch Cricket.

In [9]:
subjects = ['Americans', 'Indians']
verbs = ['play', 'watch']
objects = ['Baseball', 'Cricket']

for subj in subjects:
    for verb in verbs:
        for obj in objects:
            res = ''
            res += subj + ' ' + verb + ' ' + obj + '.'
            print(res)

Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


### Task 3
Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre- Theophile Vandermonde.

In [3]:
import numpy as np
input = [1,2,3,4,5,6]

def get_vander_matrix(input, n=3):
    length = len(input)
    res = np.zeros((length, n)).astype('int')
    for i in range(length):
        for j in range(n):
            res[i][j] = input[i]**j
    return res

print( get_vander_matrix(input, 7) )

[[    1     1     1     1     1     1     1]
 [    1     2     4     8    16    32    64]
 [    1     3     9    27    81   243   729]
 [    1     4    16    64   256  1024  4096]
 [    1     5    25   125   625  3125 15625]
 [    1     6    36   216  1296  7776 46656]]
